server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: lb:http://localhost:client-service
          predicates:
            - Path=/api/client/**
        - id: contract-service
          uri: lb:http://contract-service
          predicates:
            - Path=/contract/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost